import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nerd Studio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-full bg-[#ececee]">
          <aside className="flex flex-col w-[258px] p-[26px_20px_8px]"></aside>
          <div>{children}</div>
        </div>
      </body>
    </html>
  );
}
